apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-opkw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-docker-python-rhtap-three-component-scenarios-opkw
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-docker-python-rhtap-three-component-scenarios-opkw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-opkw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-opkw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-sruv-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-opkw@sha256:460bf33ac56ac6966c911a6d308212db96255304bb59572704a86e9bfaace6ab
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
